---
title: "EP03-respuesta-equipo-3"
author: "Equipo 3"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true # Activa la tabla de contenidos (índice)
    toc_float: true # Permite que el índice se mueva al hacer scroll
    toc_depth: 3 # Define la cantidad de niveles de títulos
    theme: flatly # Tema visual (bootstrap)
    highlight: tango # Define el estilo del código (colores)
    df_print: paged # Hace paginado al mostrar data frames
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo      = TRUE, # Muestra código R en el documento
  warning   = FALSE, # Oculta advertencias
  message   = FALSE, # Oculta mensajes (como los de carga de paquetes)
  fig.align = "center", # Centra imágenes
  fig.width = 7,
  fig.height = 4 # Parámetros para el tamaño de gráficas
)
```

---

# Contexto

En una planta química hay dos máquinas que envasan detergentes industriales en bidones con un volumen de producto que sigue una distribución normal con desviación estándar de 1 litro. La ingeniera a cargo de la planta debe asegurar que los bidones se están llenando con una media de 10 litros. Pero ella tiene la sospecha de que hay desviaciones en esta media, lo que piensa confirmar usando una muestra aleatoria de 100 envases (50 de cada una de las máquinas). También cree que hay diferencia en el cumplimiento del volumen requerido entre la máquina más antigua y la más moderna, que han de andar por el 90% y 96% de los bidones, respectivamente.

---

# Captura de datos

---

# Pregunta 1

> **Si la ingeniera está seguro de que el verdadero volumen medio no puede ser superior a 10 litros y piensa rechazar la hipótesis nula cuando la muestra presente una media menor a 9,8 litros, ¿cuál es la probabilidad de que cometa un error de tipo I? Para responder, generen un gráfico de la distribución muestral de las medias hipotetizada en donde se marque la zona correspondiente a la probabilidad solicitada, para luego, basándose en este gráfico, calcular el área correspondiente. Tome como ejemplo los scripts presentados en la lectura sobre poder estadístico.**

---

# Pregunta 2

>**Si el verdadero volumen medio de los bidones fuera de 9,85 litros, ¿cuál sería la probabilidad de que la ingeniera, que obviamente no conoce este dato, cometa un error de tipo II? Para responder, agregue al gráfico anterior la verdadera distribución muestral de las medias y marquen (con otro color) la zona correspondiente a la probabilidad solicitada, para luego, basándose en este gráfico, calcular el área correspondiente. También hay ejemplos de este procedimiento en la lectura sobre poder estadístico.**

---

# Pregunta 3

>**Como no se conoce el verdadero volumen medio, genere un gráfico del poder estadístico con las condiciones anteriores, pero suponiendo que el verdadero volumen medio podría variar de 9,5 a 10 litros. Hay un ejemplo de este tipo de gráfico en la lectura sobre poder estadístico.**

---

# Pregunta 4

>**Considerando la suposición de que el verdadero volumen medio de los bidones es de 9,85 litros, ¿cuántos bidones deberían revisarse para conseguir un poder estadístico de 0,75 y un nivel de significación de 0,05?**

---

# Pregunta 5

>**¿Alcanzaría esta muestra para detectar la diferencia que la ingeniera sospecha que existe entre las dos máquinas de la planta con al menos las mismas probabilidades de cometer errores?**

